#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"AlwaysOnDM", {PERSISTENT, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT, STRING, "main_en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastAgnosPowerMonitorShutdown", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_DriverMonitoringUncertain", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSomResetTriggered", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSignatures", {CLEAR_ON_MANAGER_START, BYTES}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT, BOOL, "0"}},
    {"RecordFront", {PERSISTENT, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"ShowDebugInfo", {PERSISTENT, BOOL}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"TermsVersion", {PERSISTENT, STRING}},
    {"TrainingVersion", {PERSISTENT, STRING}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"Version", {PERSISTENT, STRING}},

    // FrogPilot variables
    {"AccelerationPath", {PERSISTENT, BOOL, "1", "0", 2}},
    {"AccelerationProfile", {PERSISTENT, INT, "2", "0", 0}},
    {"AdjacentLeadsUI", {PERSISTENT, BOOL, "1", "0", 3}},
    {"AdjacentPath", {PERSISTENT, BOOL, "0", "0", 3}},
    {"AdjacentPathMetrics", {PERSISTENT, BOOL, "0", "0", 3}},
    {"AdvancedCustomUI", {PERSISTENT, BOOL, "0", "0", 2}},
    {"AdvancedLateralTune", {PERSISTENT, BOOL, "0", "0", 3}},
    {"AdvancedLongitudinalTune", {PERSISTENT, BOOL, "0", "0", 3}},
    {"AggressiveFollow", {PERSISTENT, FLOAT, "1.25", "1.25", 2}},
    {"AggressiveJerkAcceleration", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"AggressiveJerkDanger", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"AggressiveJerkDeceleration", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"AggressiveJerkSpeed", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"AggressiveJerkSpeedDecrease", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"AlertVolumeControl", {PERSISTENT, BOOL, "0", "0", 2}},
    {"AlwaysOnLateral", {PERSISTENT, BOOL, "1", "0", 0}},
    {"AlwaysOnLateralLKAS", {PERSISTENT, BOOL, "1", "0", 2}},
    {"ApiCache_DriveStats", {PERSISTENT, JSON, "{}", "{}"}},
    {"AutomaticallyDownloadModels", {PERSISTENT, BOOL, "1", "0", 1}},
    {"AutomaticUpdates", {PERSISTENT, BOOL, "1", "1", 0}},
    {"AvailableModelNames", {PERSISTENT, STRING, "", "", 1}},
    {"AvailableModels", {PERSISTENT, STRING, "", "", 1}},
    {"BlacklistedModels", {PERSISTENT, STRING, "", "", 2}},
    {"BlindSpotMetrics", {PERSISTENT, BOOL, "1", "0", 3}},
    {"BlindSpotPath", {PERSISTENT, BOOL, "1", "0", 1}},
    {"BorderMetrics", {PERSISTENT, BOOL, "0", "0", 3}},
    {"CalibratedLateralAcceleration", {PERSISTENT, FLOAT, "2.0", "2.0", 2}},
    {"CalibrationProgress", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"CameraView", {PERSISTENT, INT, "3", "0", 2}},
    {"CancelDownloadMaps", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"CancelModelDownload", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"CancelThemeDownload", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"CarMake", {PERSISTENT, STRING, "mock", "mock", 0}},
    {"CarModel", {PERSISTENT, STRING, "MOCK", "MOCK", 0}},
    {"CarModelName", {PERSISTENT, STRING, "", "", 0}},
    {"CECurves", {PERSISTENT, BOOL, "0", "0", 1}},
    {"CECurvesLead", {PERSISTENT, BOOL, "0", "0", 1}},
    {"CELead", {PERSISTENT, BOOL, "0", "0", 1}},
    {"CEModelStopTime", {PERSISTENT, FLOAT, "8.0", "0.0", 2}},
    {"CESignalLaneDetection", {PERSISTENT, BOOL, "1", "0", 2}},
    {"CESignalSpeed", {PERSISTENT, FLOAT, "55.0", "0.0", 2}},
    {"CESlowerLead", {PERSISTENT, BOOL, "0", "0", 1}},
    {"CESpeed", {PERSISTENT, FLOAT, "0.0", "0.0", 1}},
    {"CESpeedLead", {PERSISTENT, FLOAT, "0.0", "0.0", 1}},
    {"CEStatus", {CLEAR_ON_OFFROAD_TRANSITION, INT, "0", "0"}},
    {"CEStopLights", {PERSISTENT, BOOL, "1", "0", 1}},
    {"CEStoppedLead", {PERSISTENT, BOOL, "0", "0", 1}},
    {"ClusterOffset", {PERSISTENT, FLOAT, "1.015", "1.015", 2}},
    {"ColorScheme", {PERSISTENT, STRING, "frog", "stock", 0}},
    {"ColorToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"Compass", {PERSISTENT, BOOL, "0", "0", 1}},
    {"ConditionalExperimental", {PERSISTENT, BOOL, "1", "0", 1}},
    {"CurvatureData", {PERSISTENT | DONT_LOG, JSON, "{}", "{}"}},
    {"CurveSpeedController", {PERSISTENT, BOOL, "1", "0", 1}},
    {"CustomAlerts", {PERSISTENT, BOOL, "0", "0", 0}},
    {"CustomCruise", {PERSISTENT, FLOAT, "1.0", "1.0", 2}},
    {"CustomCruiseLong", {PERSISTENT, FLOAT, "5.0", "5.0", 2}},
    {"CustomPersonalities", {PERSISTENT, BOOL, "0", "0", 2}},
    {"CustomThemes", {PERSISTENT, BOOL, "1", "0", 0}},
    {"CustomUI", {PERSISTENT, BOOL, "1", "0", 1}},
    {"DebugMode", {CLEAR_ON_OFFROAD_TRANSITION, BOOL, "0", "0"}},
    {"DecelerationProfile", {PERSISTENT, INT, "1", "0", 2}},
    {"DeveloperMetrics", {PERSISTENT, BOOL, "1", "0", 3}},
    {"DeveloperSidebar", {PERSISTENT, BOOL, "1", "0", 3}},
    {"DeveloperSidebarMetric1", {PERSISTENT, INT, "1", "0", 3}},
    {"DeveloperSidebarMetric2", {PERSISTENT, INT, "2", "0", 3}},
    {"DeveloperSidebarMetric3", {PERSISTENT, INT, "3", "0", 3}},
    {"DeveloperSidebarMetric4", {PERSISTENT, INT, "4", "0", 3}},
    {"DeveloperSidebarMetric5", {PERSISTENT, INT, "5", "0", 3}},
    {"DeveloperSidebarMetric6", {PERSISTENT, INT, "6", "0", 3}},
    {"DeveloperSidebarMetric7", {PERSISTENT, INT, "7", "0", 3}},
    {"DeveloperUI", {PERSISTENT, BOOL, "0", "0", 3}},
    {"DeveloperWidgets", {PERSISTENT, BOOL, "1", "0", 3}},
    {"DeviceManagement", {PERSISTENT, BOOL, "1", "0", 1}},
    {"DeviceShutdown", {PERSISTENT, INT, "9", "33", 1}},
    {"DisableOnroadUploads", {PERSISTENT, BOOL, "0", "0", 2}},
    {"DisableOpenpilotLongitudinal", {PERSISTENT, BOOL, "0", "0", 0}},
    {"DiscordUsername", {PERSISTENT, STRING, "", "", 0}},
    {"DisengageVolume", {PERSISTENT, INT, "101", "101", 2}},
    {"DistanceButtonControl", {PERSISTENT, INT, "1", "0", 2}},
    {"DistanceIconPack", {PERSISTENT, STRING, "stock", "stock", 0}},
    {"DistanceIconToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"DownloadableColors", {PERSISTENT, STRING, "", ""}},
    {"DownloadableDistanceIcons", {PERSISTENT, STRING, "", ""}},
    {"DownloadableIcons", {PERSISTENT, STRING, "", ""}},
    {"DownloadableSignals", {PERSISTENT, STRING, "", ""}},
    {"DownloadableSounds", {PERSISTENT, STRING, "", ""}},
    {"DownloadableWheels", {PERSISTENT, STRING, "", ""}},
    {"DownloadAllModels", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"DownloadMaps", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"DriverCamera", {PERSISTENT, BOOL, "0", "0", 1}},
    {"DrivingModel", {PERSISTENT, STRING, "wmi-model_default", "wmi-model_default", 1}},
    {"DrivingModelName", {PERSISTENT, STRING, "WMI model (Default)", "WMI model (Default)", 1}},
    {"DrivingModelVersion", {PERSISTENT, STRING, "v9", "v9", 1}},
    {"DynamicPathWidth", {PERSISTENT, BOOL, "0", "0", 2}},
    {"DynamicPedalsOnUI", {PERSISTENT, BOOL, "1", "0", 1}},
    {"EngageVolume", {PERSISTENT, INT, "101", "101", 2}},
    {"Fahrenheit", {PERSISTENT, BOOL, "0", "0", 3}},
    {"FlashPanda", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"ForceAutoTune", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ForceAutoTuneOff", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ForceFingerprint", {PERSISTENT, BOOL, "0", "0", 2}},
    {"ForceOffroad", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"ForceOnroad", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"ForceStops", {PERSISTENT, BOOL, "0", "0", 2}},
    {"ForceTorqueController", {PERSISTENT, BOOL, "0", "0", 3}},
    {"FPSCounter", {PERSISTENT, BOOL, "1", "0", 3}},
    {"FrogPilotCarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES, "", ""}},
    {"FrogPilotCarParamsPersistent", {PERSISTENT, BYTES, "", ""}},
    {"FrogPilotDongleId", {PERSISTENT | DONT_LOG, STRING, "", "", 0}},
    {"FrogPilotStats", {PERSISTENT | DONT_LOG, JSON, "{}", "{}"}},
    {"FrogPilotTogglesUpdated", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"FrogsGoMoosTweak", {PERSISTENT, BOOL, "1", "0", 2}},
    {"GoatScream", {PERSISTENT, BOOL, "0", "0", 1}},
    {"GreenLightAlert", {PERSISTENT, BOOL, "0", "0", 0}},
    {"HideAlerts", {PERSISTENT, BOOL, "0", "0", 2}},
    {"HideLeadMarker", {PERSISTENT, BOOL, "0", "0", 2}},
    {"HideMaxSpeed", {PERSISTENT, BOOL, "0", "0", 2}},
    {"HideSpeed", {PERSISTENT, BOOL, "0", "0", 2}},
    {"HideSpeedLimit", {PERSISTENT, BOOL, "0", "0", 2}},
    {"HigherBitrate", {PERSISTENT, BOOL, "0", "0", 2}},
    {"HolidayThemes", {PERSISTENT, BOOL, "1", "0", 0}},
    {"HumanAcceleration", {PERSISTENT, BOOL, "1", "0", 2}},
    {"HumanFollowing", {PERSISTENT, BOOL, "1", "0", 2}},
    {"HumanLaneChanges", {PERSISTENT, BOOL, "1", "0", 2}},
    {"IconPack", {PERSISTENT, STRING, "frog-animated", "stock", 0}},
    {"IconToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"IncreasedStoppedDistance", {PERSISTENT, FLOAT, "0.0", "0.0", 1}},
    {"IncreasedStoppedDistanceLowVisibility", {PERSISTENT, FLOAT, "0.0", "0.0", 2}},
    {"IncreasedStoppedDistanceRain", {PERSISTENT, FLOAT, "0.0", "0.0", 2}},
    {"IncreasedStoppedDistanceRainStorm", {PERSISTENT, FLOAT, "0.0", "0.0", 2}},
    {"IncreasedStoppedDistanceSnow", {PERSISTENT, FLOAT, "0.0", "0.0", 2}},
    {"IncreaseFollowingLowVisibility", {PERSISTENT, FLOAT, "0.0", "0.0", 2}},
    {"IncreaseFollowingRain", {PERSISTENT, FLOAT, "0.0", "0.0", 2}},
    {"IncreaseFollowingRainStorm", {PERSISTENT, FLOAT, "0.0", "0.0", 2}},
    {"IncreaseFollowingSnow", {PERSISTENT, FLOAT, "0.0", "0.0", 2}},
    {"IncreaseThermalLimits", {PERSISTENT, BOOL, "0", "0", 2}},
    {"IssueReported", {CLEAR_ON_MANAGER_START, JSON, "{}", "{}"}},
    {"KonikDongleId", {PERSISTENT, STRING, "", "", 0}},
    {"KonikMinutes", {PERSISTENT, INT, "0", "0", 0}},
    {"LaneChanges", {PERSISTENT, BOOL, "1", "1", 0}},
    {"LaneChangeTime", {PERSISTENT, FLOAT, "1.0", "0.0", 1}},
    {"LaneDetectionWidth", {PERSISTENT, FLOAT, "0.0", "0.0", 1}},
    {"LaneLinesWidth", {PERSISTENT, FLOAT, "4.0", "2.0", 2}},
    {"LastMapsUpdate", {PERSISTENT, STRING, "", ""}},
    {"LateralTune", {PERSISTENT, BOOL, "1", "0", 1}},
    {"LeadDepartingAlert", {PERSISTENT, BOOL, "0", "0", 0}},
    {"LeadDetectionThreshold", {PERSISTENT, INT, "35", "50", 3}},
    {"LeadInfo", {PERSISTENT, BOOL, "1", "0", 3}},
    {"LKASButtonControl", {PERSISTENT, INT, "5", "0", 2}},
    {"LockDoors", {PERSISTENT, BOOL, "1", "0", 0}},
    {"LockDoorsTimer", {PERSISTENT, INT, "0", "0", 0}},
    {"LongDistanceButtonControl", {PERSISTENT, INT, "5", "0", 2}},
    {"LongitudinalActuatorDelay", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"LongitudinalActuatorDelayStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"LongitudinalTune", {PERSISTENT, BOOL, "1", "0", 0}},
    {"LoudBlindspotAlert", {PERSISTENT, BOOL, "0", "0", 0}},
    {"LowVoltageShutdown", {PERSISTENT, FLOAT, "11.8", "11.8", 3}},
    {"ManualUpdateInitiated", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"MapAcceleration", {PERSISTENT, BOOL, "0", "0", 1}},
    {"MapboxPublicKey", {PERSISTENT | DONT_LOG, STRING, "", "", 0}},
    {"MapBoxRequests", {PERSISTENT, JSON, "{}", "{}"}},
    {"MapboxSecretKey", {PERSISTENT | DONT_LOG, STRING, "", "", 0}},
    {"MapDeceleration", {PERSISTENT, BOOL, "0", "0", 1}},
    {"MapdSettings", {PERSISTENT, JSON, "{}", "{}"}},
    {"MapGears", {PERSISTENT, BOOL, "0", "0", 2}},
    {"MapsSelected", {PERSISTENT, STRING, "", "", 0}},
    {"MapSpeedLimit", {CLEAR_ON_MANAGER_START, FLOAT, "0.0", "0.0"}},
    {"MaxDesiredAcceleration", {PERSISTENT, FLOAT, "4.0", "2.0", 2}},
    {"MinimumBackupSize", {PERSISTENT, INT, "0", "0"}},
    {"MinimumLaneChangeSpeed", {PERSISTENT, FLOAT, "20.0", "20.0", 2}},
    {"ModelDownloadProgress", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"ModelDrivesAndScores", {PERSISTENT, JSON, "{}", "{}"}},
    {"ModelRandomizer", {PERSISTENT, BOOL, "0", "0", 2}},
    {"ModelToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"ModelUI", {PERSISTENT, BOOL, "1", "0", 2}},
    {"NavigationUI", {PERSISTENT, BOOL, "1", "0", 1}},
    {"NNFF", {PERSISTENT, BOOL, "1", "0", 2}},
    {"NNFFLite", {PERSISTENT, BOOL, "1", "0", 2}},
    {"NNFFModelName", {CLEAR_ON_MANAGER_START, STRING, "", "", 0}},
    {"NoLogging", {PERSISTENT, BOOL, "0", "0", 2}},
    {"NoUploads", {PERSISTENT, BOOL, "0", "0", 2}},
    {"NudgelessLaneChange", {PERSISTENT, BOOL, "1", "0", 0}},
    {"NumericalTemp", {PERSISTENT, BOOL, "1", "0", 3}},
    {"Offset1", {PERSISTENT, FLOAT, "5.0", "0.0", 0}},
    {"Offset2", {PERSISTENT, FLOAT, "5.0", "0.0", 0}},
    {"Offset3", {PERSISTENT, FLOAT, "5.0", "0.0", 0}},
    {"Offset4", {PERSISTENT, FLOAT, "5.0", "0.0", 0}},
    {"Offset5", {PERSISTENT, FLOAT, "10.0", "0.0", 0}},
    {"Offset6", {PERSISTENT, FLOAT, "10.0", "0.0", 0}},
    {"Offset7", {PERSISTENT, FLOAT, "10.0", "0.0", 0}},
    {"OneLaneChange", {PERSISTENT, BOOL, "1", "0", 2}},
    {"OnroadDistanceButton", {PERSISTENT, BOOL, "0", "0", 0}},
    {"OnroadDistanceButtonPressed", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"openpilotMinutes", {PERSISTENT, INT, "0", "0", 0}},
    {"OverpassRequests", {PERSISTENT, JSON, "{}", "{}"}},
    {"PathEdgeWidth", {PERSISTENT, FLOAT, "20.0", "0.0", 2}},
    {"PathWidth", {PERSISTENT, FLOAT, "6.1", "5.9", 2}},
    {"PauseAOLOnBrake", {PERSISTENT, BOOL, "0", "0", 1}},
    {"PauseLateralOnSignal", {PERSISTENT, BOOL, "0", "0", 1}},
    {"PauseLateralSpeed", {PERSISTENT, FLOAT, "0.0", "0.0", 1}},
    {"PedalsOnUI", {PERSISTENT, BOOL, "0", "0", 1}},
    {"PreferredSchedule", {PERSISTENT, INT, "2", "0", 0}},
    {"PreviousSpeedLimit", {PERSISTENT, FLOAT, "0.0", "0.0"}},
    {"PromptDistractedVolume", {PERSISTENT, INT, "101", "101", 2}},
    {"PromptVolume", {PERSISTENT, INT, "101", "101", 2}},
    {"QOLLateral", {PERSISTENT, BOOL, "1", "0", 1}},
    {"QOLLongitudinal", {PERSISTENT, BOOL, "1", "0", 1}},
    {"QOLVisuals", {PERSISTENT, BOOL, "1", "0", 0}},
    {"RadarTracksUI", {PERSISTENT, BOOL, "0", "0", 3}},
    {"RainbowPath", {PERSISTENT, BOOL, "0", "0", 1}},
    {"RandomEvents", {PERSISTENT, BOOL, "0", "0", 1}},
    {"RandomThemes", {PERSISTENT, BOOL, "0", "0", 1}},
    {"RandomThemesHolidays", {PERSISTENT, BOOL, "0", "0", 1}},
    {"ReduceAccelerationLowVisibility", {PERSISTENT, INT, "0", "0", 2}},
    {"ReduceAccelerationRain", {PERSISTENT, INT, "0", "0", 2}},
    {"ReduceAccelerationRainStorm", {PERSISTENT, INT, "0", "0", 2}},
    {"ReduceAccelerationSnow", {PERSISTENT, INT, "0", "0", 2}},
    {"ReduceLateralAccelerationLowVisibility", {PERSISTENT, INT, "0", "0", 2}},
    {"ReduceLateralAccelerationRain", {PERSISTENT, INT, "0", "0", 2}},
    {"ReduceLateralAccelerationRainStorm", {PERSISTENT, INT, "0", "0", 2}},
    {"ReduceLateralAccelerationSnow", {PERSISTENT, INT, "0", "0", 2}},
    {"RefuseVolume", {PERSISTENT, INT, "101", "101", 2}},
    {"RelaxedFollow", {PERSISTENT, FLOAT, "1.75", "1.75", 2}},
    {"RelaxedJerkAcceleration", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"RelaxedJerkDanger", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"RelaxedJerkDeceleration", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"RelaxedJerkSpeed", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"RelaxedJerkSpeedDecrease", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"ReverseCruise", {PERSISTENT, BOOL, "0", "0", 1}},
    {"RoadEdgesWidth", {PERSISTENT, FLOAT, "2.0", "2.0", 2}},
    {"RoadNameUI", {PERSISTENT, BOOL, "1", "0", 1}},
    {"RotatingWheel", {PERSISTENT, BOOL, "1", "0", 1}},
    {"ScreenBrightness", {PERSISTENT, INT, "101", "101", 2}},
    {"ScreenBrightnessOnroad", {PERSISTENT, INT, "101", "101", 2}},
    {"ScreenManagement", {PERSISTENT, BOOL, "1", "0", 1}},
    {"ScreenRecorder", {PERSISTENT, BOOL, "1", "0", 2}},
    {"ScreenTimeout", {PERSISTENT, INT, "30", "30", 2}},
    {"ScreenTimeoutOnroad", {PERSISTENT, INT, "30", "10", 2}},
    {"SecOCKeys", {PERSISTENT | DONT_LOG, STRING, "", "", 0}},
    {"SetSpeedLimit", {PERSISTENT, BOOL, "0", "0", 1}},
    {"SetSpeedOffset", {PERSISTENT, FLOAT, "0.0", "0.0", 2}},
    {"ShowCEMStatus", {PERSISTENT, BOOL, "1", "0", 2}},
    {"ShowCPU", {PERSISTENT, BOOL, "1", "0", 3}},
    {"ShowCSCStatus", {PERSISTENT, BOOL, "1", "0", 2}},
    {"ShowGPU", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ShowIP", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ShowMemoryUsage", {PERSISTENT, BOOL, "1", "0", 3}},
    {"ShownToggleDescriptions", {PERSISTENT, JSON, "{}", "{}"}},
    {"ShowSLCOffset", {PERSISTENT, BOOL, "1", "0", 0}},
    {"ShowSpeedLimits", {PERSISTENT, BOOL, "1", "0", 1}},
    {"ShowSteering", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ShowStoppingPoint", {PERSISTENT, BOOL, "1", "0", 3}},
    {"ShowStoppingPointMetrics", {PERSISTENT, BOOL, "1", "0", 3}},
    {"ShowStorageLeft", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ShowStorageUsed", {PERSISTENT, BOOL, "0", "0", 3}},
    {"SidebarMetrics", {PERSISTENT, BOOL, "1", "0", 3}},
    {"SidebarOpen", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SignalAnimation", {PERSISTENT, STRING, "frog", "stock", 0}},
    {"SignalMetrics", {PERSISTENT, BOOL, "0", "0", 3}},
    {"SignalToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"SLCConfirmation", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SLCConfirmationHigher", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SLCConfirmationLower", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SLCFallback", {PERSISTENT, INT, "2", "0", 1}},
    {"SLCLookaheadHigher", {PERSISTENT, INT, "0", "0", 2}},
    {"SLCLookaheadLower", {PERSISTENT, INT, "0", "0", 2}},
    {"SLCMapboxFiller", {PERSISTENT, BOOL, "1", "0", 1}},
    {"SLCOverride", {PERSISTENT, INT, "1", "0", 1}},
    {"SLCPriority", {PERSISTENT, STRING, "", "", 2}},
    {"SLCPriority1", {PERSISTENT, STRING, "Map Data", "Map Data", 2}},
    {"SLCPriority2", {PERSISTENT, STRING, "Dashboard", "Dashboard", 2}},
    {"SNGHack", {PERSISTENT, BOOL, "1", "0", 2}},
    {"SoundPack", {PERSISTENT, STRING, "frog", "stock", 0}},
    {"SoundToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"SpeedLimitAccepted", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"SpeedLimitChangedAlert", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SpeedLimitController", {PERSISTENT, BOOL, "1", "0", 0}},
    {"SpeedLimitFiller", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SpeedLimits", {PERSISTENT | DONT_LOG, JSON, "[]", "[]"}},
    {"SpeedLimitsFiltered", {PERSISTENT | DONT_LOG, JSON, "[]", "[]"}},
    {"SpeedLimitSources", {PERSISTENT, BOOL, "0", "0", 3}},
    {"StandardFollow", {PERSISTENT, FLOAT, "1.45", "1.45", 2}},
    {"StandardJerkAcceleration", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"StandardJerkDanger", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"StandardJerkDeceleration", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"StandardJerkSpeed", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"StandardJerkSpeedDecrease", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"StandbyMode", {PERSISTENT, BOOL, "0", "0", 1}},
    {"StartAccel", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StartAccelStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StartupMessageBottom", {PERSISTENT, STRING, "Human-tested, frog-approved 🐸", "Always keep hands on wheel and eyes on road", 0}},
    {"StartupMessageTop", {PERSISTENT, STRING, "Hop in and buckle up!", "Be ready to take over at any time", 0}},
    {"StaticPedalsOnUI", {PERSISTENT, BOOL, "0", "0", 1}},
    {"SteerDelay", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerDelayStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerFriction", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerFrictionStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerKP", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerKPStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerLatAccel", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerLatAccelStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerRatio", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerRatioStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StockDongleId", {PERSISTENT, STRING, "", ""}},
    {"StopAccel", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StopAccelStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StoppedTimer", {PERSISTENT, BOOL, "0", "0", 1}},
    {"StoppingDecelRate", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StoppingDecelRateStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SubaruSNG", {PERSISTENT, BOOL, "1", "0", 2}},
    {"TacoTune", {PERSISTENT, BOOL, "0", "0", 2}},
    {"TacoTuneHacks", {PERSISTENT, BOOL, "0", "0", 2}},
    {"TestAlert", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"TetheringEnabled", {PERSISTENT, INT, "0", "0", 0}},
    {"ThemeDownloadProgress", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"ThemesDownloaded", {PERSISTENT, JSON, "{}", "{}"}},
    {"Timezone", {PERSISTENT, STRING, "", ""}},
    {"TinygradUpdateAvailable", {PERSISTENT, BOOL, "0", "0", 1}},
    {"ToyotaDoors", {PERSISTENT, BOOL, "1", "0", 0}},
    {"TrafficFollow", {PERSISTENT, FLOAT, "0.5", "0.5", 2}},
    {"TrafficJerkAcceleration", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"TrafficJerkDanger", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"TrafficJerkDeceleration", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"TrafficJerkSpeed", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"TrafficJerkSpeedDecrease", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"TuningLevel", {PERSISTENT, INT, "0", "0", 0}},
    {"TuningLevelConfirmed", {PERSISTENT, BOOL, "0", "0", 0}},
    {"TurnDesires", {PERSISTENT, BOOL, "0", "0", 2}},
    {"UnlockDoors", {PERSISTENT, BOOL, "1", "0", 0}},
    {"Updated", {PERSISTENT, STRING, "0", "0"}},
    {"UpdateSpeedLimits", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"UpdateSpeedLimitsStatus", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"UpdateTinygrad", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"UpdateWheelImage", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"UseActiveTheme", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"UseKonikServer", {PERSISTENT, BOOL, "0", "0", 2}},
    {"UseSI", {PERSISTENT, BOOL, "1", "1", 3}},
    {"UseVienna", {PERSISTENT, BOOL, "0", "0", 1}},
    {"VEgoStarting", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"VEgoStartingStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"VEgoStopping", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"VEgoStoppingStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"VeryLongDistanceButtonControl", {PERSISTENT, INT, "6", "0", 2}},
    {"VoltSNG", {PERSISTENT, BOOL, "0", "0", 2}},
    {"WarningImmediateVolume", {PERSISTENT, INT, "101", "101", 2}},
    {"WarningSoftVolume", {PERSISTENT, INT, "101", "101", 2}},
    {"WeatherPresets", {PERSISTENT, BOOL, "0", "0", 2}},
    {"WeatherToken", {PERSISTENT | DONT_LOG, STRING, "", "", 2}},
    {"WheelControls", {PERSISTENT, STRING, "", "", 2}},
    {"WheelIcon", {PERSISTENT, STRING, "frog", "stock", 0}},
    {"WheelSpeed", {PERSISTENT, BOOL, "0", "0", 2}},
    {"WheelToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
};
