name: Create Branch and Setup Sync Workflow

on:
  workflow_dispatch:
    inputs:
      remote_repo_url:
        description: 'Remote Repository URL'
        required: true
      remote_branch_name:
        description: 'Remote Branch Name'
        required: true
      new_branch_name:
        description: 'New Branch Name'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: main
      - name: Create Sync Workflow File in Main Branch
        run: |
          mkdir -p .github/workflows
          secret_placeholder='$'"{${{ '{' }} secrets.PAT ${{ '}' }}}"
          cat << EOF > .github/workflows/sync_${{ github.event.inputs.new_branch_name }}.yml
          name: Sync ${{ github.event.inputs.new_branch_name }}
      
          on:
            schedule:
              - cron: "0 9 * * *"
            workflow_dispatch:
      
          jobs:
            sync:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v4
                  with:
                    ref: ${{ github.event.inputs.new_branch_name }}
                    persist-credentials: false
                - name: Sync with Remote Repo
                  uses: repo-sync/github-sync@v2.3.0
                  with:
                    source_repo: "${{ github.event.inputs.remote_repo_url }}"
                    source_branch: "${{ github.event.inputs.remote_branch_name }}"
                    destination_branch: "${{ github.event.inputs.new_branch_name }}"
                    github_token: $secret_placeholder
          EOF

                

        
      - name: Commit and Push Workflow File to Main Branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'BRid37'
          git config --global user.email '55640145+BRid37@users.noreply.github.com'
          git add .github/workflows/sync_${{ github.event.inputs.new_branch_name }}.yml
          git commit -m "Add sync workflow for ${{ github.event.inputs.new_branch_name }}"
          git push origin main
          
      - name: Checkout and Push New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          # Setup git configuration
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Clone the remote repository to a temporary directory
          git clone ${{ github.event.inputs.remote_repo_url }} temp_repo
          cd temp_repo
          
          # Checkout the specified remote branch
          git checkout ${{ github.event.inputs.remote_branch_name }}
          
          # Create a new branch from it (this step might be optional if you're just tracking the remote branch)
          git checkout -b ${{ github.event.inputs.new_branch_name }}
          
          # Add your repository as a new remote and push the branch
          git remote add personal_repo https://x-access-token:${{ secrets.PAT }}@github.com/BRid37/opAIO.git
          git push personal_repo ${{ github.event.inputs.new_branch_name }}:refs/heads/${{ github.event.inputs.new_branch_name }}
          
          # Cleanup
          cd ..
          rm -rf temp_repo

          
      

        




