name: repo maintenance

on:
  schedule:
    - cron: "0 * * * *"  # every hour for COMMA_HACK 5
  workflow_dispatch:

jobs:
  package_updates:
    name: package_updates
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/commaai/openpilot-base:latest
    if: github.repository == 'commaai/openpilot'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: uv lock
      run: |
        python3 -m ensurepip --upgrade
        pip3 install uv
        uv lock --upgrade
    - name: bump submodules
      run: |
        git config --global --add safe.directory '*'
        git -c submodule."tinygrad".update=none submodule update --remote
        git add .
    - name: update car docs
      run: |
        scons -j$(nproc) --minimal opendbc_repo
        PYTHONPATH=. python selfdrive/car/docs.py
        git add docs/CARS.md
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@9153d834b60caba6d51c9b9510b087acf9f33f83
      with:
        author: Vehicle Researcher <user@comma.ai>
        token: ${{ secrets.ACTIONS_CREATE_PR_PAT }}
        commit-message: Update Python packages
        title: '[bot] Update Python packages'
        branch: auto-package-updates
        base: master
        delete-branch: true
        body: 'Automatic PR from repo-maintenance -> package_updates'
        labels: bot
