name: Sync FrogPilot-Staging

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2.3.0
      with:
        source_repo: "https://github.com/FrogAi/FrogPilot.git"
        source_branch: "FrogPilot-Staging"
        destination_branch: "fp-FrogPilot-Staging"
        github_token: ${{ secrets.PAT }}

    - name: Cherry-pick commit
      run: |
        git config --global user.email "55640145+BRid37@users.noreply.github.com"
        git config --global user.name "BRid37"
        git fetch --all
        git checkout fp-canfd-patch
        git checkout fp-FrogPilot-Staging
        git cherry-pick dd91e916a94ad3ca4230aa20e8de6c93351a0a57
        

    - name: Push changes
      run: |
        git push origin fp-FrogPilot-Staging
