name: Sync FrogPilot-Staging

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2.3.0
        with:
          source_repo: "https://github.com/FrogAi/FrogPilot.git"
          source_branch: "FrogPilot-Staging"
          destination_branch: "fp-FrogPilot-Staging"
          github_token: ${{ secrets.PAT }}

      - name: Find commit hash by name and revert
        run: |
          git checkout fp-FrogPilot-Staging
          git stash -u -m "Save local changes"
          commit=$(git rev-parse "Compile FrogPilot")
          echo "Commit to revert: $commit"
          git revert -n $commit

      - name: Cherry-pick commit
        run: |
          git config --global user.email "55640145+BRid37@users.noreply.github.com"
          git config --global user.name "BRid37"
          git cherry-pick 88fa811c7cb7e11969900872171c45ca690495d0

      - name: Push changes
        run: |
          git push origin fp-FrogPilot-Staging
